### ISSUE TITLE
Rich Text Editor should not destroy markdown

### ISSUE THREAD

**Issue by laurent22** [cwesson/joplin-plugin-typograms#1]
This issue was reported on the Joplin repository but it's not something that we can fix since the change needs to be done on the plugin:

https://github.com/laurent22/joplin/issues/9929

**Comment by cwesson** [comment]
A complete fix for this depends on [laurent22/joplin#10315](https://github.com/laurent22/joplin/issues/10315).  The current fix works as long as the typogram does not have leading whitespace.  As a workaround, any non-whitespace character can be added at the beginning of the typogram.

**Comment by laurent22** [comment]
That's great, thanks @cwesson! We'll look at fixing this whitespace issue

**Comment by cwesson** [comment]
Fixed in v1.0.1 with Joplin v3.0.13.
