### ISSUE TITLE
Display bug on Android app

### ISSUE THREAD

**Issue by JaneX8** [cwesson/joplin-plugin-typograms#2]
CSS is shown when using

```typogram
          +----+     o    |          o       *      *   .----------.
  *-+---. '-* -+-    |    v         ^         \    /    |.--------.|
    |   '--->   +----+  ->*<-      /   .-+->*<-o--+     |'------> ||
  <-'       *---+     |<----->|   +----' |  ^   \       '---------'|
                                         |__|    v      *----------'
```

```typogram
+----+
|    |---> My first diagram!
+----+
```

![Screenshot_20240924_205649_Joplin.jpg](https://github.com/user-attachments/assets/c7f1c3f3-4bc8-4932-bfa7-ac7244abb311)

![Screenshot_20240924_205653_Joplin.jpg](https://github.com/user-attachments/assets/9d8ad286-cc82-4a82-916c-367734c34428)

**Comment by cwesson** [comment]
I have not been able to reproduce this issue with Joplin Mobile v3.1.3 and Typograms plugin v1.0.1.  What version of Joplin and the Typograms plugin are you using?

**Comment by JaneX8** [comment]
Samsung Galaxy S24 Ultra
OneUI 6.1
Android 14

**Joplin 3.0.8 (prod, android)**

Sync Version: 3
Profile Version: 47
Keychain Supported: No

ABC Sheet Music Plugin: 1.0.5
AlertsPerfect: 1.0.1
Copy Code Blocks: 1.1.2
Inline tags: 1.3.0
Joplin Calendar: 1.2.0
Link Graph UI: 1.5.0
Spoilers: 1.0.6
**Typograms: 1.0.1**

Android API level: 34
WebView version: 128.0.6613.146
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1

**Comment by JaneX8** [comment]
After trial and error. Interestingly there is interference between plugins.

The combination with 
Copy Code Blocks: 1.1.2

Causes the issue.

**Comment by cwesson** [comment]
Interesting, thanks for the info.  I'll look in to it.
